// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuj1hOS73lt6xGetJjTRyuxJBwKdPFRy4',
    appId: '1:718405976085:android:7d7cde9471eb1452face1c',
    messagingSenderId: '718405976085',
    projectId: 'craftblend-fa31e',
    storageBucket: 'craftblend-fa31e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRhu2Isvvsncn7Ao4yxVOoThkm3H9RigY',
    appId: '1:718405976085:ios:9a2e90407d526396face1c',
    messagingSenderId: '718405976085',
    projectId: 'craftblend-fa31e',
    storageBucket: 'craftblend-fa31e.firebasestorage.app',
    iosBundleId: 'com.example.craftBlendProject',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDIEoh7cEsOTbMrPSZKpe3pYmRTX4l5Z6s",
      authDomain: "craftblend-c388a.firebaseapp.com",
      projectId: "craftblend-c388a",
      storageBucket: "craftblend-c388a.firebasestorage.app",
      messagingSenderId: "607198615953",
      appId: "1:607198615953:web:5d7bfa57ab2faa3c962230",
      measurementId: "G-9RPVNG7G43");
}
